# Generated by Django 4.0.3 on 2022-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
